---
#
# Play01 - 웹서버 설정
#
- name: Restore playbook.yml
  hosts: all
  vars_files:
    - vars/vars.yml
  tasks:
# 1) 방화벽 - http, https
    - name: 4) 방화벽 - {{ fw_80 }}, {{ fw_8080 }}
      ansible.posix.firewalld:
        service: "{{ item }}"
        state: disabled
        permanent: true
        immediate: true
      loop:
        - "{{ fw_80 }}"
        - "{{ fw_8080 }}"
# 2) 웹 서비스 기동 - httpd, firewalld
    - name: 3) 웹 서비스 기동 - {{ svc_web }}, {{ svc_fw }}
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - "{{ svc_web }}"
        - "{{ svc_fw }}"
# 3) 웹 서비스 설정 - /var/www/html/index.html
    - name: 2) 웹 서비스 설정 - {{ inx_dst }}
      ansible.builtin.file:
       path: "{{ inx_dst }}"
       state: absent
# 4) 웹패키지 삭제 - httpd, mod_ssl, firewalld
    - name: 4) 웹패키지 삭제 - {{ pkg_http }}, {{ pkg_https }}
      ansible.builtin.dnf:
        name:
         - "{{ pkg_http }}"
         - "{{ pkg_https }}"
        state: absent
